### ISSUE TITLE
Incorrect GPG URL

### ISSUE THREAD

**Issue by ILoveYaToo** [zerotier/install.zerotier.com#11]
Hi,

The incorrect GPG url is provided on https://www.zerotier.com/download/. This results in an error when trying to install using the more secure instructions. The incorrect GPG url given is `https://raw.githubusercontent.com/zerotier/download.zerotier.com/master/htdocs/contact%40zerotier.com.gpg`

**Comment by ketominer** [comment]
It's been a few days and https://raw.githubusercontent.com/zerotier/download.zerotier.com/master/htdocs/contact%40zerotier.com.gpg is still missing...

**Comment by TechplexEngineer** [comment]
Looks like they might have renamed the github repository from `download` to `install` and the complementary github redirect grace period has ended.

It looks like the solution is as simple a changing the word **download** to **install** in the command listed on the [download page](https://www.zerotier.com/download/). For example:

```
curl -s 'https://raw.githubusercontent.com/zerotier/install.zerotier.com/master/htdocs/contact%40zerotier.com.gpg' | gpg --import && \
if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash; fi
```

**Comment by laduke** [comment]
looks like it's been updated
