### ISSUE TITLE
installation not working on Buster

### ISSUE THREAD

**Issue by JOduMonT** [zerotier/install.zerotier.com#4]
Hi;

when I try to install zerotier on Debian 10 (Buster) it just don't reconize it; the script just jump to 
```
else
    echo "*** FAILED: unrecognized or ancient distribution: $dvers"
exit 1
```

The mistake is probably how the script identify Buster at the [line 175](https://github.com/zerotier/install.zerotier.com/blob/master/htdocs/install.sh#L175) but I was'nt able to debug it :(

Note : on my machine `cat /etc/debian_version ` return `buster/sid`
and [`cat /etc/debian_version | cut -d '.' -f 1 | cut -d '/' -f 1`](https://github.com/zerotier/install.zerotier.com/blob/master/htdocs/install.sh#L136) return `buster`

> Remark : It's a similar issue of #3

### So I install it by shrinking the debian part like this :
```
if [ -f /etc/debian_version ]; then
	dvers=`cat /etc/debian_version | cut -d '.' -f 1 | cut -d '/' -f 1`
	$SUDO rm -f /tmp/zt-sources-list
	echo '*** Found Debian "buster", or "sid" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
	echo "deb ${ZT_BASE_URL_HTTP}debian/buster buster main" >/tmp/zt-sources-list
...
```

> Remark : I change the line originaly [177](https://github.com/zerotier/install.zerotier.com/blob/master/htdocs/install.sh#L177) for `/buster buster main` instead of `/buster stretch main`

**Comment by jodumont** [comment]
ok so I found the mistake with this push it will work for everyone
https://github.com/zerotier/install.zerotier.com/pull/5

**Comment by joelstitch** [comment]
This is happening to me but using kali-rolling.

This is what I get when I try to install it: 

```
*** Detecting Linux Distribution

*** FAILED: unrecognized or ancient distribution: kali-rolling
```

**Comment by JOduMonT** [comment]
@joelstitch saddly the maintainer seams to not want any help and take his own decision

he remove kali from the install file
https://github.com/zerotier/install.zerotier.com/blob/master/install.sh.in#L176

and never accept my PR
https://github.com/zerotier/install.zerotier.com/pull/7/commits/ad1335619f762772e3d8d237379b7f3899499057

**Comment by JOduMonT** [comment]
@joelstitch saddly the maintainer seams to not want any help and take his own decision

he remove kali from the install file
https://github.com/zerotier/install.zerotier.com/blob/master/install.sh.in#L176

and never accept my PR
https://github.com/zerotier/install.zerotier.com/pull/7/commits/ad1335619f762772e3d8d237379b7f3899499057
