### ISSUE TITLE
Cannot install on fresh install of ubuntu 22.04

### ISSUE THREAD

**Issue by brett-fz** [zerotier/install.zerotier.com#49]
Hi guys, I have just spun up a new VPS and went to install ZeroTier and I am getting the following error:

`ubuntu@vps-app-dev-001:~$ curl -s https://install.zerotier.com | sudo bash

*** ZeroTier Service Quick Install for Unix-like Systems

*** Tested OSes / distributions:

***   MacOS (10.13+) (just installs ZeroTier One.pkg)
***   Debian Linux (7+)
***   RedHat/CentOS Linux (6+)
***   Fedora Linux (16+)
***   SuSE Linux (12+)
***   Mint Linux (20+)
***   Kali Linux (2024.1+)

*** Supported architectures vary by OS / distribution. We try to support
*** every system architecture supported by the target.

*** Please report problems by opening a GitHub issue or Pull Request at:
*** https://github.com/zerotier/install.zerotier.com
*** Please include the content of `/etc/os-release` for your distribution.

*** Detecting Linux Distribution

bash: line 291: [: missing `]'
bash: line 291: ubuntu: command not found
*** Unknown or unsupported distribution! Aborting.
ubuntu@vps-app-dev-001:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

ubuntu@vps-app-dev-001:~$
`

**Comment by glimberg** [comment]
whoops.  hold one just a few minutes and I'll get that fixed

**Comment by brett-fz** [comment]
> whoops. hold one just a few minutes and I'll get that fixed

Cheers mate, I manually added the missing brackets so I could install while waiting for the merge request.

**Comment by glimberg** [comment]
Should be all set now.  Sorry about that.

**Comment by brett-fz** [comment]
> Should be all set now. Sorry about that.

Cheers mate, no dramas.
