### ISSUE TITLE
Debian installer is not working bc VERSION_ID is empty

### ISSUE THREAD

**Issue by Susensio** [zerotier/install.zerotier.com#57]
The variable `$VERSION_ID` used in
https://github.com/zerotier/install.zerotier.com/blob/ed81856b7cf150018a00b02df0f9287b33a0bff8/install.sh.in#L281-L305
Is read from `/etc/os-release` but does not exists for Debian testing.

Same problem can be observed in https://github.com/ValveSoftware/steam-for-linux/issues/9857

Old bug report of this problem https://groups.google.com/g/linux.debian.bugs.dist/c/AYCKa0HZzSI

A possible solution may be to assume that an empty `VERSION_ID` is `debian:testing` or `debian:sid`, and using `MAX_SUPPORTED_DEBIAN_VERSION`

**Comment by glimberg** [comment]
Fix has been deployed.  Thanks!
