### ISSUE TITLE
error installing on Ubuntu 20.04.6 LTS:   503  Service Unavailable [IP: 184.31.60.188 443]

### ISSUE THREAD

**Issue by ab-chesspad** [zerotier/install.zerotier.com#98]
curl -s https://install.zerotier.com | sudo bash

*** ZeroTier Service Quick Install for Unix-like Systems

*** Tested OSes / distributions:

***   MacOS (10.13+) (just installs ZeroTier One.pkg)
***   Debian Linux (7+)
***   RedHat/CentOS Linux (6+)
***   Fedora Linux (16+)
***   SuSE Linux (12+)
***   Mint Linux (20+)
***   Kali Linux (2024.1+)

*** Supported architectures vary by OS / distribution. We try to support
*** every system architecture supported by the target.

*** Please report problems by opening a GitHub issue or Pull Request at: 
*** https://github.com/zerotier/install.zerotier.com
*** Please include the content of `/etc/os-release` for your distribution.

*** Detecting Linux Distribution

*** Detected Ubuntu Linux, creating /etc/apt/sources.list.d/zerotier.list
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease                                                                     
Get:3 http://download.zerotier.com/debian/focal focal InRelease [20.5 kB]                                                     
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]                                                       
Get:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [128 kB]                                      
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [65.2 kB]                                      
Err:7 https://repo.skype.com/deb stable InRelease                                                                                
  503  Service Unavailable [IP: 184.31.60.188 443]
Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 DEP-11 Metadata [212 B]                        
Get:9 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [160 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [276 kB]                        
Hit:11 http://ppa.launchpad.net/alex-p/smplayer/ubuntu focal InRelease                                   
Get:12 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [940 B]         
Get:13 http://us.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 DEP-11 Metadata [212 B]
Get:14 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [446 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:16 http://us.archive.ubuntu.com/ubuntu focal-backports/main amd64 DEP-11 Metadata [7,996 B]
Get:17 http://us.archive.ubuntu.com/ubuntu focal-backports/restricted amd64 DEP-11 Metadata [212 B]
Get:18 http://us.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [30.5 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 DEP-11 Metadata [212 B]
Fetched 1,392 kB in 1s (1,824 kB/s)  
Reading package lists... Done
W: Failed to fetch https://repo.skype.com/deb/dists/stable/InRelease  503  Service Unavailable [IP: 184.31.60.188 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gpg is already the newest version (2.2.19-3ubuntu2.2).
gpg set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ubuntu-advantage-tools : Depends: ubuntu-pro-client (>= 31.2.2~20.04) but 31.2~20.04 is to be installed
 ubuntu-pro-client-l10n : Depends: ubuntu-pro-client (= 31.2.3~20.04) but 31.2~20.04 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

*** Installing zerotier-one package...
Get:1 http://download.zerotier.com/debian/focal focal InRelease [20.5 kB]
Err:2 https://repo.skype.com/deb stable InRelease                                                                                
  503  Service Unavailable [IP: 184.31.60.188 443]
Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease                                 
Hit:4 http://ppa.launchpad.net/alex-p/smplayer/ubuntu focal InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 20.5 kB in 1s (22.9 kB/s)
Reading package lists... Done
W: Failed to fetch https://repo.skype.com/deb/dists/stable/InRelease  503  Service Unavailable [IP: 184.31.60.188 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ubuntu-advantage-tools : Depends: ubuntu-pro-client (>= 31.2.2~20.04) but 31.2~20.04 is to be installed
 ubuntu-pro-client-l10n : Depends: ubuntu-pro-client (= 31.2.3~20.04) but 31.2~20.04 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

*** Package installation failed! Unfortunately there may not be a package
*** for your architecture or distribution. For the source go to:
*** https://github.com/zerotier/ZeroTierOne
===========================================
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by laduke** [comment]
i think repo.skype.com is something in your apt config

**Comment by glimberg** [comment]
also the other dependency errors:

```
The following packages have unmet dependencies:
ubuntu-advantage-tools : Depends: ubuntu-pro-client (>= 31.2.220.04) but 31.220.04 is to be installed
ubuntu-pro-client-l10n : Depends: ubuntu-pro-client (= 31.2.320.04) but 31.220.04 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Don't think this issue has anything to do with the install script, but rather dependency issues that already exist on your system.  You'll have to fix those.  You can "reset" things by removing `/etc/apt/sources.list.d/zerotier.list` and try to run the install script again once you've cleared up the other errors.

**Comment by ab-chesspad** [comment]
ok, ran
sudo apt --fix-broken install
as the script suggested, resolved an issue and installed successfully
Sorry for this confusion

**Comment by ab-chesspad** [comment]
my bad

**Comment by glimberg** [comment]
No problem.  Glad you got it working!
